version: '2.0'
services:
  keydb1:
    image: eqalpha/keydb
    command: 
    - keydb-server
    - /etc/keydb/redis.conf
    - --port
    - "6379"
    - --replicaof
    - 'keydb2'
    - '6379'
    - --active-replica
    - 'yes'
  keydb2:
    image: eqalpha/keydb
    command: 
    - keydb-server
    - /etc/keydb/redis.conf
    - --port
    - "6379"
    - --replicaof
    - 'keydb1' 
    - '6379'
    - --active-replica
    - 'yes'
  ruby:
    image: ruby:2.5
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./:/keydb-test
